name: mcp-anon-oterm

services:
  oterm:
    image: oterm
    pull_policy: never
    build:
      context: .
    environment:
      OLLAMA_URL: http://ollama:11434
    links:
    - ollama
    - mcp-anon
  ollama:
    image: ollama/ollama
    ports:
    - "11434:11434"
    volumes:
    - ./.ollama:/root/.ollama
  mcp-anon:
    image: mcp-anon
    pull_policy: never
    build:
      context: ../..
    command:
    - --transport
    - http
    volumes:
    - ../gemini-cli/basic/example.csv:/opt/app/workdir/example.csv

