name: mcp-anon-oterm

include:
- ../../docker-compose.yaml

services:
  oterm:
    image: oterm
    pull_policy: never
    build:
      context: .
    environment:
      OLLAMA_URL: http://ollama:11434
    links:
    - ollama
    - mcp-anon-http
    depends_on:
      mcp-anon-http:
        condition: service_started
        required: false
  ollama:
    image: ollama/ollama
    ports:
    - "11434:11434"
    volumes:
    - ./.ollama:/root/.ollama

